### ISSUE TITLE
Doesn't work in test files with go 1.8 beta

### ISSUE THREAD

**Issue by blitzprog** [fatih/color#48]
Please see https://github.com/golang/go/issues/18153.
Only `go test` is affected.

**Comment by fatih** [comment]
You're right. You have to explicitly set `color.NoColor = false` so that it works. I've made a comment there: https://github.com/golang/go/issues/18153#issuecomment-264388969 I'm not sure what the underlying change is. I want to first understand it before I try to fix it here or if it's an issue at https://github.com/mattn/go-isatty (@mattn)

**Comment by fatih** [comment]
This is now fixed in go tip. Thanks @blitzprog for the feedback again.
