### ISSUE TITLE
Feature request : colorizing the stdin - keyboard input in the terminal

### ISSUE THREAD

**Issue by bhargavbhegde7** [fatih/color#72]
Please consider adding this feature for colorizing the keyboard input too.

**Comment by fatih** [comment]
Can you please give more information on what you want ?

**Comment by prataprc** [comment]
The issue is the following:

I am implementing a tabular reporting for tn47/goledger. In that, the content
for each cell is formatted first, which is agnostic of coloring details.
Coloring options are confined to Rendering functions.

Given this situation my code looks like the following

```go
	rcf.paddcells()
	fmsg := rcf.Fmsg(" %%-%vs%%-%vs%%%vs\n")

	for i, cols := range rcf.rows {
		items := []interface{}{cols[0]}
		if i < 2 {
			items = append(items, cols[1], cols[2])
		} else {
			items = append(items, api.YellowFn(cols[1]), CommodityColor(db, comm, cols[2])))
		}
		fmt.Fprintf(outfd, fmsg, items...)
	}
```

The issue is the last line ``fmt.Fprintf``, that takes ``fmsg`` which is
constructed during runtime.

Some of the cells need to be yellow, while others default to terminal's
foreground, and the entire row is formatted and render by ``fmt.Fprintf``.

Refer: [code](https://github.com/tn47/goledger/blob/master/reports/report_balance.go#L154)

**Comment by prataprc** [comment]
I have a draft implementation that works for me, if it looks okay I can raise a pull request.

Refer: [fix](https://github.com/prataprc/color/commit/641ad7e7584555d4fcf030e88d398cbc3c73284a)

Thanks,

**Comment by bhargavbhegde7** [comment]
It would be great if there was a way to set custom color for the input text. I am using `bufio.NewReader(os.Stdin)ReadString('\n')` to get the user input from the keyboard in a console application, and I don't see a way to achieve this.

**Comment by fatih** [comment]
You can force to enable the color with `color.NoColor = false`, which overrides the automatic detection, and thus enables color for you. Thanks.
